### ISSUE TITLE
gl.xml: GL_NV_path_rendering needs functionality from EXT_direct_state_access, not available in GLES

### ISSUE THREAD

**Issue by null77** [KhronosGroup/OpenGL-Registry#117]
The extension for GL_NV_path_rendering states:

When NV_path_rendering is advertised, the following functionality must be supported...
The following entry points (specified by the EXT_direct_state_access extension) MUST be supported:

   void MatrixLoadfEXT(enum matrixMode, const float *m);
   void MatrixLoaddEXT(enum matrixMode, const double *m);
(snip)

However these entry points are never mentioned in gl.xml, and EXT_direct_state_access is not mentioned as a GLES extension. Maybe these entry points be added to gl.xml under this extension, instead of under EXT_direct_state_access, since that is not specified as a GLES extension.

This is making life hard for my auto-generation script. @oddhack any possible resolution?

**Comment by oddhack** [comment]
Those were definitely left out, but I need to get clarification from NVIDIA on #119 and the double-precision entry points before moving forward. It wouldn't be appropriate to move them from EXT_dsa to NV_path_rendering since they are part of both extensions, but they can certainly be added to NV_path_rendering.

**Comment by null77** [comment]
Thanks Jon for following up.
