### ISSUE TITLE
Link to <GL/wgl.h> is missing on the Index Page

### ISSUE THREAD

**Issue by tommai78101** [KhronosGroup/OpenGL-Registry#256]
Link to page: https://www.khronos.org/registry/OpenGL/index_gl.php#headers

Currently, a hyperlink to <GL/wgl.h> header file is missing on the page. Or it may be missing information, explaining why <GL/wgl.h> header file is removed from the page.

Missing link to <GL/wgl.h>:

https://www.khronos.org/registry/OpenGL/api/GL/wgl.h

**Comment by oddhack** [comment]
While we do have the capability to generate a wgl.h, AFAIK nobody has ever even verified that it works on Windows platforms. We expect people are using Microsoft's wgl.h. So, we haven't promoted its existence because we can't recommend its use.

**Comment by tommai78101** [comment]
Can this explanation be added to the API and Extensions Header section? I feel this is important to add, since you're still able to link and obtain the Khronos Group <wgl.h> implementation. And wouldn't that cause confusion if you're able to access the link, but you can't find it anywhere on the site?

Personally, I just feel confused why there are two <wgl.h> and why they are so different because of the licensing.

**Comment by tommai78101** [comment]
Now I'm thinking about it, Microsoft's <gl/GL.h> is weird. I do not even see anything mentioning where Microsoft's latest <wgl.h> header is at.

The licensing is different, because Microsoft's <gl/GL.h> is by Silicon Graphics, and the <wgl.h> is Khronos Groups. That's fine. The Khronos Group's <wgl.h> has more OpenGL extensions functions that does not exist on the <gl/GL.h> by Microsoft.

All in all, do you just want someone to verify if <wgl.h> works flawlessly on a Windows system? Or there is this stringent testing protocol for headers to verify if the header is working or not? (As in, it has to be tested from Windows 95 all the way to Windows 10 1809?)

**Comment by oddhack** [comment]
TBH it's been about 20 years since I've looked at Microsoft's headers. Probably their WGL interfaces come from somewhere in windows.h, so I misspoke about that.

The point of the separation between wgl.h and wglext.h was to reflect that Microsoft did not update the headers they ship to include new vendor WGL extensions. So we provided them in wglext.h to layer on top of the WGL interfaces in the Microsoft headers. The latter interfaces *should* correspond to what's in the wgl.h we provide, and if you're able to compile with our wgl.h instead of Microsoft's headers and get a functioning app, I'd take that as a pretty good sign our wgl.h can be used - but it's hard to imagine a circumstance where you can use our wgl.h without including windows.h, so it seems hard to test. I'd be interested to hear what your experience is. We don't have conformance testing for this stuff, only for the underlying OpenGL driver functionality.

I'm sorry the licensing situation is confusing. Without Microsoft's help, there's nothing we can do to improve the headers they ship, so we've worked around it as best we can. I expect most developers these days are using loader layers like GLEW, if not middleware layers, and isolate themselves from the underlying OS to considerable degree by doing that.

**Comment by tommai78101** [comment]
> It's hard to imagine a circumstance where you can use our wgl.h without including windows.h, so it seems hard to test. I'd be interested to hear what your experience is. We don't have conformance testing for this stuff, only for the underlying OpenGL driver functionality.

You're in luck today, because I was actually testing out the <wgl.h> header from the OpenGL Registry since 2 weeks ago, and it worked fine. (And even if I don't have <Windows.h> included, it's still going to be part of the <wgl.h> since it's defined in there.)

But in order for <wgl.h> to work fine, you still need to include <gl/GL.h> from Microsoft, because the typedef `GLenum` is  defined in the <gl/GL.h> header. So the WGL interfaces doesn't actually come from <Windows.h> but it's from <gl/GL.h>.

Because it's so flawless (only with the <gl/GL.h> header from Windows SDK), I thought someone maintaining the OpenGL Registry pages forgot to include <wgl.h> header file link, so that's why I bought it up today.

**Comment by pdaniell-nv** [comment]
@tommai78101 Can we close this issue since you have a work-around?

**Comment by tommai78101** [comment]
Sure. I thought it's on the contributor's end to determine whether this issue should be closed or not.
