### ISSUE TITLE
General and specific problems with gl.xml

### ISSUE THREAD

**Issue by stohrendorf** [KhronosGroup/OpenGL-Registry#282]
# Intention
So, I know there are already multiple issues and PRs about gl.xml, but I'd like to summarize a few problems I encountered while trying to write a generator using C++14 features. Please note: this is just a collection of ideas I had while trying to process gl.xml, and thus the proposals mentioned here are not perfect, and are surely incomplete.

What I'm trying to achieve is this (extracts from what my generator currently produces).
API Header:
```cpp
enum class TextureNormalModeEXT : core::EnumType
{
#if defined(WITH_API_EXTENSION_GL_EXT_texture_perturb_normal)
#if defined(WITH_GL_API_VENDOR_SGI)
    PerturbExt = 0x85AE,
#endif // defined(WITH_GL_API_VENDOR_SGI)
#endif // defined(WITH_API_EXTENSION_GL_EXT_texture_perturb_normal)
}; // enum TextureNormalModeEXT
// <snip>
#if defined(WITH_API_EXTENSION_GL_ARB_vertex_array_object)
extern void bindVertexArray(uint32_t array);
extern void deleteVertexArray(core::SizeType n, const uint32_t *arrays);
extern void genVertexArray(core::SizeType n, uint32_t *arrays);
extern bool isVertexArray(uint32_t array);
#endif // defined(WITH_API_EXTENSION_GL_ARB_vertex_array_object)
```

API implementation/wrapper:
```cpp
void begin(PrimitiveType mode)
{
    glBegin(static_cast<GLenum>(mode));
}
```
Feature selection (which does not really work, as e.g. `glEnable` is not referenced by API version 4.3 and requires `API_LEVEL_GL_VERSION_1_0`, which enables several deprecated/retired features):
```cpp
#define API_LEVEL_GL_VERSION_4_3
#define WITH_GL_API_VENDOR_ARB
```

# General problems
The structure of the XML is confusing, especially the use of the names "enum" and "group"; also, API levels/versions (called "feature" in the XML) are not properly handled.

## enum/group
Proposal: Restructure the XML to contain an element `/registry/constants`, looking something like this, defining all constants available, regardless of any constraints:
```xml
<constants>
    <constant value="0x00000001" symbol="GL_CURRENT_BIT"/>
    ...
```
Also, restructure the XML to contain an element `/registry/enums`, containing all constant groups that are logically grouped into an enum, looking something like this:
```xml
<enums>
    <enum symbol="LightTexturePNameEXT">
      <reference constant="GL_ATTENUATION_EXT"/>
      ...
```

A `reference` element references constants (see below).

## Features
Proposal: Rename to "API", and introduce names "flavor" (for gl, gles, gles2, etc.) and version (a semver-like versioning scheme, allowing strict ordering, e.g. "1.0", "4.3", etc., for defining the version of the flavor the API definition is valid for.)

APIs may reference extensions.

Example:
```xml
<api flavor="gles1" version="1.0" symbol="GL_VERSION_ES_CM_1_0">
    <profile>
        <reference constant="GL_DEPTH_BUFFER_BIT"/>
        <reference command="glDisable"/>
        <reference extension="GL_OES_fixed_point"/>
    ...
    <profile symbol="common">
    ...
  ...
  <extension symbol="GL_OES_fixed_point">
    <constrained flavor="gl" version-min="1.0" version-max="1.9">
      <reference ...
    <constrained flavor="gl" version-min="2.0">
      <reference ...
```

## Constraints
Proposal: Define the concept of "constraint", allowing to restrict existence of constants and commands to selected API levels/flavors/versions, extensions, profiles, etc.

## Versioning
Constants/enums/commands are usually restricted to specific versions of APIs. Proposal: add (optional) `version-{min,max}` attributes to restrict validity of symbols (see above).

# Specific problems
Without further ado, here's the log of my WIP generator, listing the problems it encountered (yes, it's a long list): https://pastebin.com/08qhACgr

**Comment by oddhack** [comment]
There's a lot to unpack here. I'll preface this by saying that we (really I, because I'm the one responsible for this infrastructure) don't have much time or interest in significant rewrites, and if we did, we'd probably start by migrating to the (derived) XML schema used by Vulkan and a bunch of other Khronos APIs. It's not totally clear which parts of this are disliked things vs. which are things you can't, or find hard to accomplish within the existing schema, but I'll try to speak to most of it.

I'll start with the enumerants. The actual original purpose of the registry was to record ("register") the enumerant blocks reserved for use by different vendors. Those are the \<enums> tags, and they are essential. As the vendors defined specific enumerants within their reserved blocks, they got added as \<enum> tags within that block, so we knew which parts of the block were unused. Similarly for bitmasks, where we had to know which bits were already in use.

The naming choices are sometimes suboptimal (as was GL's choice to use 'GLenum' instead of 'int'). Trying to use actual C enumerated types wasn't a GL design consideration, and AFAIK it's not entirely possible to do so, since a handful of the tokens would have to be included in multiple unrelated enumerated types. 

I'm not following the issue about versioning. Each version of ES or GL introduces a new set of interfaces, and in one case, removed a set of interfaces via the profile mechanism. That's what the \<require> and \<remove> tags in the XML express. What additional information do you need beyond that? An interface is present starting in the lowest version that requires it, and is absent starting in the lowest version that removes it (and in one case, is present again when it's reintroduced later :-) ). There is some expressive ability on the require/remove tags to apply only for specific APIs or profiles, which is used here and there. So these are are a form of constraint.

It's true that there isn't an explicit set of dependencies of form e.g. "GL 4.0 requires GL 3.3". Instead the processing scripts we use are told to select a set of features. This does decouple some information from the XML, in return for making it easy to explicitly control what core versions and extensions get included - which is necessary for generating the gl.h / glext.h split (unfortunately forced on us by Microsoft's implementation, decades ago) and some other obscure use cases.

I'm not sure what your use case is for the preprocessor stuff. A dynamic selection of the versions and extensions present in the header at compile time? That will run into some complex dependency issues in cases where multiple extensions / core versions require the same underlying definition. In our scripts, we don't try to deal with any of that. We just do a transitive dependency propagation of the required versions and extensions, and emit the resulting interfaces in dependency order. To the extent that anyone requires a customized C header - and we're not even sure if anyone does - we want them to generate it themselves, using our scripts.

In sum, I think most if not all of the information you're after is already available, but not in the form you want it. We are very conservative about schema changes when the current one is used by multiple tools inside and outside Khronos, and any changes would affect all existing users. So if there's something you need to know that literally cannot be determined from the existing schema, we can talk about how to express that, and perhaps add it in a way that is likely to be safely ignored by existing consumers. However, wholesale schema revisions are very unlikely to happen.

WRT the specific problems your generator came up with, most of those appeared to be either typos in the enum \<group> tags (should be fixed now), or noting that the groups are incomplete. Per #280, while we'll accept additions to the groupsas people come up with them, this isn't going to be a priority for our own time. If there were some other issues raised in the generator output, I missed them amidst the many typo / incomplete reports. A lot of this sort of stuff in other parts of the API is caught by the existing generator scripts; since the groups are unused by those scripts, there are no sanity checks or validation performed on them beyond verifying the XML is consistent with the RNC schema.

**Comment by stohrendorf** [comment]
Sorry, I just forgot to close this issue, which probably would have prevented you from taking time to write such a lengthy (and good) response. I mostly agree to what was said, except for being conservative about changes, but I'm not in the position to question that. Most of the problems I had came from the naming conventions as I said above, and also that I overlooked a very crucial information about symbol removal and symbol inheritance across versions.

That said, I managed to get my generator into a working (but not yet perfect) state and now make full use of constant groups (aka enums), see here: https://github.com/stohrendorf/EdisonEngine/tree/master/src/render/gl/api - if you're interested in having the generator script as part of this repository, drop me a note, and I'll try to polish it and push it over.

Cheers

**Comment by oddhack** [comment]
I think we'd be happy to link to your project, but we don't want to include external stuff like this because it introduces an expectation that we would maintain it - which we probably wouldn't. Lots of bad experience with this in the past. Khronos is mostly focused on generating specs and SDKs and conformance suites, but not much beyond that. Even the Vulkan-Hpp (C++ bindings for Vulkan) project, which has somewhat official status and work on which is supported by a Khronos member, is treated as a separate project.

**Comment by stohrendorf** [comment]
I fully understand that, than you :)
