### ISSUE TITLE
Are LGPU_SEPARATE_STORAGE_BIT_NVX and PER_GPU_STORAGE_BIT_NV the same thing?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-Registry#33]
I'm fixing #4 and noticed that these two enums (in NV_gpu_multicast and NVX_linked_gpu_multicast) are both BufferStorage bits, with the same value, but different names. The spec language appears (effectively) identical for both, but I wanted to make sure these are intended to be semantically the same and can share the BufferStorage behavior.

Also, the MapBufferUsageMask \<enums> group in gl.xml currently has bits 0x0800 and 0x1000 reserved by Joshua Schnarr, jschnarr@nvidia.com, so I also wanted to verify that this use is consistent with whatever Joshua had planned.

**Comment by oddhack** [comment]
Likewise I see that GL_MAX_LGPU_GPUS_NVX and GL_MULTICAST_GPUS_NV share the same value across the two specs.

**Comment by jschnarr-nv** [comment]
Yes, LGPU_SEPARATE_STORAGE_BIT_NVX and PER_GPU_STORAGE_BIT_NV are equivalent. Likewise MAX_LGPU_GPUS_NVX and MULTICAST_GPUS_NV. The collision is intentional.

Yes this is was the intended use of the reserved bits. We decided to drop the bit that was going to use 0x1000. That reservation can be freed.

Thanks.

**Comment by oddhack** [comment]
@jschnarr-nv thanks. The headers and gl.xml have been updated - please check them out, if you get a chance.
