### ISSUE TITLE
[xml] Commands added in multiple versions of "gl" api

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#364]
```
glProgramParameteri
glGetIntegeri_v
glBindBufferRange
glBindBufferBase
```
Note, i'm not including `glGetPointerv` because it is properly specified to be deprecated in 3.2 and undeprecated in 4.3 .

I'm not sure about `glProgramParameteri` because both of it's additions are in the same version (4.1), in `<require>` tags which are next to each other :
```
        <require comment="Reuse commands from ARB_get_program_binary">
            ...
            <command name="glProgramParameteri"/>
            ...
        </require>
        <require comment="Reuse commands from ARB_separate_shader_objects">
            ...
            <command name="glProgramParameteri"/>
            ...
        </require>
```
It doesn't make it less uncomfortable to parse, but at least it's understandable: 2 separate extensions 
 had same command and both got added to core in same version.

`glGetIntegeri_v`, `glBindBufferRange` and `glBindBufferBase` are all added 2 times, in 3.0 and 3.1 versions, which doesn't make much sense to me.

**Comment by Perksey** [comment]
This is a non-issue in most cases, but it is entirely possible that these functions were redefined for clarity purposes, or some other reason. It makes so difference for literally every parser out there, but if you really want something done about it I suggest you PR it in.

**Comment by SunSerega** [comment]
In my current parser i check everything which can be wrong or at least unexpected. That's how i found all previous issues.

The basic rule is - there should be programmable explanation with no exception for everything. Or in other words - nothing hardcoded. And for now it works with surprisingly little amount of problems. Only thing left without checks is extensions.

> it is entirely possible that these functions were redefined for clarity purposes

There isn't any comment about this in xml. And i think it only makes sense to specify it in specification.

Also, there is really nothing to redefine about something like `glGetIntegeri_v`.

And that's exactly what's uncomfortable about these commands. I looks weird, meaning something may need to be done to them. But there is no comment or anything else (at least in what i found) saying why this behavior would be a thing.

IMO ignoring this is just wrong, so for while this issue is up - i have warnings added to console and log of my parser.

> I suggest you PR

I'm storing issue's here for 2 main purposes:

1. Hoping someone who knows to explain why;
2. To have a list checked by someone except me, containing things that can be improved.

If there would be open issues in this list when i get time to fix them myself - i would make PR.

But i would first at least make sure that most of improvable things relevant to myself are in this list, so that i can fix them all at once.

**Comment by SunSerega** [comment]
In my current parser i check everything which can be wrong or at least unexpected. That's how i found all previous issues.

The basic rule is - there should be programmable explanation with no exception for everything. Or in other words - nothing hardcoded. And for now it works with surprisingly little amount of problems. Only thing left without checks is extensions.

> it is entirely possible that these functions were redefined for clarity purposes

There isn't any comment about this in xml. And i think it only makes sense to specify it in specification.

Also, there is really nothing to redefine about something like `glGetIntegeri_v`.

And that's exactly what's uncomfortable about these commands. I looks weird, meaning something may need to be done to them. But there is no comment or anything else (at least in what i found) saying why this behavior would be a thing.

IMO ignoring this is just wrong, so for while this issue is up - i have warnings added to console and log of my parser.

> I suggest you PR

I'm storing issue's here for 2 main purposes:

1. Hoping someone who knows to explain why;
2. To have a list checked by someone except me, containing things that can be improved.

If there would be open issues in this list when i get time to fix them myself - i would make PR.

But i would first at least make sure that most of improvable things relevant to myself are in this list, so that i can fix them all at once.

**Comment by Perksey** [comment]
If this issue is a major issue for you I advise you wait for comments from a spec editor. Thanks.

**Comment by oddhack** [comment]
Some of the duplication has to do with internal documentation purposes for what extension(s) introduced certain interfaces when promoted, some of it probably dates back to the GL 3.0 / 3.1 core profile mess where things got taken out and put back in, and there are probably a few accidentally duplicated cases.

WRT processing the XML, the dependency-driven nature of it means that duplication is harmless; basic GL data types have hundreds or thousands of duplicate dependencies generated from all the API calls that use them. If you want to propose removing a duplication on the grounds that it's actually *wrong*, e.g. some version or extension is expressing a dependency for something that actually isn't defined or reintroduced by that version extension, and you are willing to conduct a search of the specs to verify that, then we'd probably be fine with accepting such a change.

But it takes a close reading of old specs to figure out if a duplication is actually wrong, and I don't want to do that without compelling need because the only visible difference it makes in almost all circumstances is which line of the generated header that interface appears on. It's up to you, but if you do want to propose some PRs along these lines, please do that separately and be clear about what sort of spec search you conducted to back up the proposed change.

In retrospect a lot of these issues seem to come up because people write their own registry processing code instead of working off the Python scripts we wrote. Those isolatel the dependency tracking logic and have a plugin framework for making different kinds of output generators based on the results of those dependencies, rather than expecting the generator itself to know anything about them. There's nothing *wrong* with rolling your own, but if it follows a different strategy or internal logic compared to our scripts, you may get unusual results, or assume that something is wrong in the XML that isn't actually wrong.

In OpenXR and Vulkan land, we've seen many more projects using the (roughly equivalent to GL) plugin framework successfully with their registries - I think OpenXR has as many as a couple of dozen different generators across the various spec and SDK and CTS tools they provide.

**Comment by SunSerega** [comment]
> If you want to propose removing a duplication on the grounds that it's actually wrong, e.g. some version or extension is expressing a dependency for something that actually isn't defined or reintroduced by that version extension, and you are willing to conduct a search of the specs to verify that, then we'd probably be fine with accepting such a change.

I know, if i would to end being the one making PR - i would do proper research and report what i found.

But this issue isn't proposal (yet). It shows (to me or someone else who would like to make a PR) that something need's to be checked and maybe done.

**Comment by Perksey** [comment]
> the dependency-driven nature of it means that duplication is harmless

I think this sums the situation up as I still strongly feel this is a non-issue.

**Comment by Perksey** [comment]
@pdaniell-nv I believe @oddhack deduced that this is a non-issue and as such a PR shouldn't be necessary.

**Comment by SunSerega** [comment]
This was an explanation why it's harmless. Which i agree it is. But i don't see any explanation for why this *should* be a thing.

**Comment by oddhack** [comment]
I don't know what to tell you other than that this is how we chose to do it.

**Comment by SunSerega** [comment]
So wait, you did actually confirm that was a conscious choice and not just typo?

**Comment by oddhack** [comment]
Put it down to quirks of the XML author if you must, but please close the issue and move on. This doesn't require any justification on our part and I don't want to spend any more time on it.

**Comment by SunSerega** [comment]
This was originally target for small cleanup. But i see, i ended up arguing about it's legitimacy as an issue (i.e. problem). Sorry for taking your time on this.

I'm opened it here thinking about discussion with someone who can answer "why", so i better understand when (if) making PR. But i guess it wasn't even right to put it here, together with actual problems, just for that.

**Comment by Perksey** [comment]
I apologise if any of our comments have come across as argumentative, but there's been a lot of nitpicks (primarily from you, but some from others) on the spec lately and to be honest it's very hard to justify, explain, and/or enact changes into such a monolithic and ageing spec.

In this particular case, it was said a number of times from the start that this is a non-issue and no further attention is required, yet the issue was open far longer than it should've been. That's not to defer further issues being raised (and yes this is the right place to report issues such as these) but persisting these issues once they're proven to be moot is far from productive.

Cleanup is a very hard thing to do in the gl spec as it isn't exactly malleable due to the amount of stakeholders and practices that have become commonplace over the 27 years that OpenGL has been around.

Again I apologise if there has been any seemingly argumentative comments from any parties involved, but spec cleanup is super hard and so are conversations regarding it. I also apologise for any inconvenience caused by the consensuses reached here.

This issue needs no further discussion.
