### ISSUE TITLE
GLSL_EXT_ray_query in OpenGL 4.6 ? 

### ISSUE THREAD

**Issue by helixd-2k18** [KhronosGroup/OpenGL-Registry#389]
I would like to make a request for OpenGL Ray Query, and there are several reasons for this.

- Availability of wrappers, libraries, OpenGL emulators based on DirectX 12 or Vulkan API.
- Ray Query is simple in that it can be supported with Compute and Fragment shaders.
- Also, `GL_KHR_shader_subgroup` from the Vulkan specification has recently been added.
- The presence of `VK_KHR_ray_tracing` and DirectX Ray Tracing in possible implementations.

Also, some games (more precisely, mods for them), in principle, cannot switch to the Vulkan API for an extremely long time.

**Comment by Perksey** [comment]
Currently, to my knowledge there's no intention to champion driver-accelerated ray-tracing in OpenGL like DirectX and Vulkan have. Wrapper vendors who wish to provide this are always welcome to provide their own extensions in the registry (raytracing in Vulkan was originally a NVIDIA-only extension called `NV_ray_tracing`) though I'm not sure if you have to be a conformant wrapper and/or Khronos member to do so (edge cases like `GREMEDY` come to mind)

But a Khronos extensions for ray-tracing related functions are unlikely to be championed into the OpenGL spec because I don't think there'll be much interest within the working group to do so. I could be wrong though!

**Comment by nwnk** [comment]
Anyone can define a GL extension, conformance isn't an issue in that sense. Conformance covers those features defined in OpenGL itself, or in KHR/ARB/OES extensions (I believe, don't quote me, not a Khronos spokesperson here).

If you want to start a draft extension spec for how you would imagine the ray tracing API to work in OpenGL, please do. If you want to go really wild, you could sketch out an implementation in a wrapper layer, or directly in an open-source OpenGL like Mesa.

**Comment by Perksey** [comment]
Would be cool to get some clarification as to whether anyone (i.e. not just Khronos members) can define OpenGL extensions and reserve blocks etc.

But as for the actual topic of this issue, I presume this can either be closed or perhaps moved to OpenGL-API (where I predict a similar feature request will reside)

**Comment by oddhack** [comment]
We aren't going to hand enum ranges out without any justification at all, but if they're a bona-fide implementer, or an ISV working with an implementer, no problem. If someone is creating an extension spec speculatively and has no way to implement it, they should use tokens in the "experimental" range until and unless they can work with an implementer.

Broadly speaking, people who aren't IHVs or partnered with IHVs probably ought to be working in the context of Mesa for whatever they're trying to do, since that's where OSS activity happens.

**Comment by pdaniell-nv** [comment]
Regarding the original question in this issue. NVIDIA have no plans to expose ray tracing, or ray queries, as an OpenGL extension. All ray tracing development for a Khronos open standard will be done in Vulkan: https://www.khronos.org/blog/ray-tracing-in-vulkan. OpenGL applications can take advantage of ray tracing in Vulkan by way of the [GL_EXT_external_objects](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_external_objects.txt) extension.

**Comment by pdaniell-nv** [comment]
I don't think there is anything else to say on this issue. Closing.
