### ISSUE TITLE
https://www.opengl.org/documentation/ links "OpenGL 3.3" to 4.5

### ISSUE THREAD

**Issue by mrmsbarnes** [KhronosGroup/OpenGL-Registry#391]
You should say there is no 3.3 documentation.  THERE'S NO 3.3 DOCUMENTATION???  Say it isn't so.  Many of us have grown to love 3.3, but we still want documentation somewhere.

**Comment by pdaniell-nv** [comment]
You can find the OpenGL 3.3 specification in the [OpenGL Registry](https://www.khronos.org/registry/OpenGL/index_gl.php). As for the reference pages, you're right that the OpenGL 3.3 link just references the OpenGL 4.5 reference pages. Since OpenGL 3.3 is a subset of OpenGL 4.5, and each reference page indicates which version of the specification the token is available in, you should have everything you need for OpenGL 3.3.

**Comment by Perksey** [comment]
This isn't an official Khronos website, but http://docs.gl/ probably has what you're looking for. As for the old opengl.org website, it doesn't look like it has a repo (otherwise I would've directed you there as this isn't really the correct repo to report this issue in)

In any case, as @pdaniell-nv was saying the OpenGL Refpages (marked as `gl4`) has what you need and covers all OpenGL versions. There is a handy version marker down at the bottom of each page - you can ignore all the functions that don't have a tick in the `3.3` box ;)

Here's an example from [the glCompressedTextureSubImage3D page](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCompressedTextureSubImage3D.xhtml):

![image](https://user-images.githubusercontent.com/11160611/79338759-bf64f600-7f1f-11ea-8287-873d4d2f5677.png)

Or you can also use the docs.gl website linked previously, which does split out OpenGL 3 documentation into its own section.

The choice is yours, but I think this issue can be closed now. Let me know if you need anything else! :)

**Comment by pdaniell-nv** [comment]
Closing.

**Comment by mrmsbarnes** [comment]
thank you both.
