### ISSUE TITLE
[xml] duplicate <enum>s (GL_NO_ERROR, GL_CONSERVATIVE_RASTER_MODE_NV).

### ISSUE THREAD

**Issue by eddyb** [KhronosGroup/OpenGL-Registry#460]
These were found while writing a new parser for `gl.xml`:
* `<feature api="glsc2" name="GL_SC_VERSION_2_0" number="2.0">`
  * `<require>`
    * 2x `<enum name="GL_NO_ERROR"/>` (lines 40311 and 40517 at 2afca877b25ec2c7f19ddcba21a8627b9fa8e026)
* `<extension name="GL_NV_conservative_raster_pre_snap_triangles" supported="gl|glcore|gles2">`
  * `<require>`
    * 2x `<enum name="GL_CONSERVATIVE_RASTER_MODE_NV"/>` (lines 48145 and 48148 at 2afca877b25ec2c7f19ddcba21a8627b9fa8e026)

**Comment by oddhack** [comment]
Fixed, thanks. N.b. while this is an oversight, it's not actually an error and has no effect on the generated headers - the XML needs to be traversed in dependency order and it's normal for the same token / command to be referenced multiple times. But it's pointless to duplicate in the same \<require> block, that's probably due to cut & paste from API specs with insufficient attention to detail.
