### ISSUE TITLE
Include complete license text

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/OpenGL-Registry#628]
DISCLAIMER: I'm not a lawyer, nor is this legal advice. Follow at your own risk.

Using the SPDX license identifier alone is an insufficient replacement for the actual license text. I've discussed this [here](https://community.khronos.org/t/registry-license-terms/111035), here's the TL;DR:
The original license text of the API headers appear to have been replaced with the SPDX ID within [this commit](https://github.com/KhronosGroup/OpenGL-Registry/commit/43aad35cba1b76ea1f33f8d6234fa57ae8e2fbbe) about three years ago, quote from the commit description:

> [@pdaniell-nv](https://github.com/pdaniell-nv) recommend approving ASAP. This has benefits downstream when doing REUSE license checking in repositories which host these files.

REUSE requires that all licenses are placed in their own dedicated folder, which hasn't been done. This repository isn't considered REUSE-compliant and follows bad licensing terms.

I'm a fan of the licensing practice used in FreeBSD (take a look at [cat.c](https://raw.githubusercontent.com/freebsd/freebsd-src/main/bin/cat/cat.c)).
Blender, on the other hand, has all the licenses in `doc/licenses` and provides the SPDX ID and copyright text at the top of each file.

And what about the extensions and specs? Are they proprietary, or not owned by Khronos?

I'd love to see these changes be made, as many loaders (Glad, GLEW, gl3w, etc.) download the headers from this repository and this could be problematic.

**Comment by oddhack** [comment]
We cannot say what the licenses on all the extensions are. It is literally impossible, many of the companies have been out of business for decades. REUSE compatibility is worth doing and I'll take a look at that, but most vendor extensions are just going to be under a placeholder "LicenseRef-Unknown" to pacify REUSE.

We are not going to start injecting full Apache 2.0 licenses in the headers, and Khronos *does* have an IP lawyer whom such matters have been discussed with.

**Comment by loneneuron** [comment]
> We cannot say what the licenses on all the extensions are. It is literally impossible, many of the companies have been out of business for decades.

Yeah, I can see what you mean. Some SGI extensions date back to the 90s.
> We are not going to start injecting full MIT or Apache 2.0 whatever licenses in the headers

Ha, the Apache license  would be longer than the header itself! However the MIT license isn't very long, sparing trouble for the loaders I mentioned... but very well then.
> Khronos does have an IP lawyer whom such matters have been discussed with.

It's good to know that a real lawyer is going to take action.
> REUSE compatibility is worth doing and I'll take a look at that

Thank you for your consideration!

**Comment by oddhack** [comment]
> It's good to know that a real lawyer is going to take action.

More that the real lawyer has long since signed off on using SPDX identifiers, so there won't be any action other than to minimally REUSE-ify the repo. Whenever you remove a file with just a copyright and SPDX ID from a repository, you'll have to carry the actual license terms with it - the advantage of the standard IDs is that this is not hard to sort out.

**Comment by loneneuron** [comment]
> Whenever you remove a file with just a copyright and SPDX ID from a repository, you'll have to carry the actual license terms with it - the advantage of the standard IDs is that this is not hard to sort out.

I can see why it's worth the minor complications, many large projects are resorting to SPDX for the same reason.

Vulkan-Docs appears to be doing this right; licenses appear to be in `LICENSES/`, the `LICENSE.adoc` makes it clear that each ID corresponds to a specific license, and `COPYING.adoc` defines the specific license of each directory... though there appears to be one minor slip-off on that repo...

The license template hasn't been modified to state the copyright years and copyright holders, and I believe that that error has made it's way to `chrome://credits` as I've stated on the forums. Search for "vulkan".
I believe that this happened because `reuse download --all` downloads them as-is, without informing.

**Comment by loneneuron** [comment]
It's been a week and no updates. This is urgent.
I've noticed several flaws in multiple repositories, Khronos' lawyers should really take action. It's embarrassing for the multi-million dollar company maintaining and developing the world's leading "*royalty-free*" open standards for 3D graphics, Virtual and Augmented Reality, Parallel Computing, Machine Learning, and Vision Processing (as stated on the Khronos homepage) to make such critical flaws in their standards and just leave them there, lying around while young developers like me are spending so much time from our precious lives, and even sacrificing health, just to learn and use these standards only to find them in such a state. Period.

**Comment by loneneuron** [comment]
It's been a week and no updates. This is urgent.

**Comment by oddhack** [comment]
Closing, since this user has deleted their account. In principle this is a moderately useful thing to do but it's not a high priority for Khronos, as people have been using these headers without trouble for decades.
