### ISSUE TITLE
Mismatch in Opengl and Opengles glBlendFunc spec with regards to NaN values arithmetic ?

### ISSUE THREAD

**Issue by MatAshish** [KhronosGroup/OpenGL-Registry#635]
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml has a statement in description section:
"However, a blend factor that should be equal to 1 is guaranteed not to modify its multiplicand, and a blend factor equal to 0 reduces its multiplicand to 0."
This statement seems to ignore the fact that if either src or dst value is NaN then blend factors do not matter and result is always NaN.

I do not see this statement in OpenGLES spec of the same function: https://registry.khronos.org/OpenGL-Refpages/es3/html/glBlendFunc.xhtml 

Was this intentionally removed in OpenGLES as part of a spec fix and not propagated to OpenGL or am i looking at a potentially different expectation from two similar APIs ?

**Comment by nwnk** [comment]
The GL 4.6 spec contains the word "guaranteed" 28 times, none of them in text talking about BlendFunc. AIUI the "reference pages" are not normative, so you'd probably need to trace their change history to find when that text was introduced. But, since they were originally man pages and BlendFunc is a very old function, the answer might be lost to pre-Khronos history.

I don't think there's any intentional difference in expectation here.

**Comment by zmike** [comment]
Discussed WG 23 Oct 2024: This is an erroneous addition to the refpages.

https://github.com/KhronosGroup/OpenGL-Refpages/ is the tree for the refpages. I've created https://github.com/KhronosGroup/OpenGL-Refpages/pull/159 which will remove the problem.
