### ISSUE TITLE
GL/glplatform.h header

### ISSUE THREAD

**Issue by abbradar** [KhronosGroup/OpenGL-Registry#9]
Generated [gl.h](https://github.com/KhronosGroup/OpenGL-Registry/blob/master/api/GL/gl.h#L39) file mentions `GL/glplatform.h`, but I can't find any mention of this file anywhere. Is there a mistake or have I just searched too shallowly?

**Comment by oddhack** [comment]
Nobody actually uses this header and it has not been throughly debugged.  That's why it isn't linked from the registry. There was some notional interest by some of the Linux distributors / Mesa folks in moving to an autogenerated header instead of their handwritten header, and to that end we woudl probably want to capture the horrid conditional logic for platform-dependent stuff in a separate glplatform.h, but we haven't closed on all the issues involved yet. I'll track this fact somehow, probably by a comment in the header. Or maybe just remove it from the tree, it can still always be built from the scripts.

**Comment by abbradar** [comment]
That was exactly what I was interested in trying (move a cross-platform package set, Nixpkgs, to those autogenerated headers instead of Mesa ones). I'll just stick to Mesa for now; thanks for the explanation!

**Comment by oddhack** [comment]
I pulled the gl.h/glx.h/wgl.h headers out of the tree and left some comments in the xml/ directory on their existence for those inclined to experiment. Hopefully that's a good medium.
