### ISSUE TITLE
GLX_MESA_swap_control missing in glx.xml

### ISSUE THREAD

**Issue by Dav1dde** [KhronosGroup/OpenGL-Registry#94]
`GLX_EXT_swap_control` and `GLX_SGI_swap_control` are included in the specification, but [`GLX_MESA_swap_control`](https://github.com/mesa3d/mesa/blob/master/docs/specs/MESA_swap_control.spec) seems to be missing.

**Comment by oddhack** [comment]
There is no registered specification for GLX_MESA_swap_control. If the Mesa folks want to provide one we can register it and add to the XML/headers, but without that we're out of luck. There are a number of other extant extensions that have no registered specs as well - I couldn't tell you the exact number because we only find out about them by accident.

I suggest you file this with the Mesa project, and ask them to open a PR here if they want to register it.

It's a reasonable issue but we have no way of resolving it, so I request you close this at least until there's something actionable associated with it.

**Comment by oddhack** [comment]
The spec author pointed me to the master copy in the Mesa tree, so registered & closed now.
